export enum TipoLogEnum {
  LOGIN = 'LOGIN',
  REGISTRO = 'REGISTRO',
  ERRO = 'ERRO',

  MOVIMENTACAO_ENTRADA = 'MOVIMENTACAO_ENTRADA',
  MOVIMENTACAO_SAIDA = 'MOVIMENTACAO_SAIDA',

  SE_DESATIVOU = 'SE_DESATIVOU',
  CANCELOU_CONSULTA = 'CANCELOU_CONSULTA',
  SOLICITOU_CONSULTA = 'SOLICITOU_CONSULTA',
  DEFERIU_CONSULTA = 'DEFERIU_CONSULTA',

  CONSULTA_INICIADA = 'CONSULTA_INICIADA',
  CONSULTA_FINALIZADA = 'CONSULTA_FINALIZADA',

  DESATIVOU_PERFIL = 'DESATIVOU_PERFIL',
  INDEFERIU_CONSULTA = 'INDEFERIU_CONSULTA',

  EDITOU_TIPO_CONSULTA = 'EDITOU_TIPO_CONSULTA',
  ADICIONOU_CLIENTE = 'ADICIONOU_CLIENTE',
  REGISTROU_PRODUTO = 'REGISTROU_PRODUTO',
  REMOVEU_PRODUTO = 'REMOVEU_PRODUTO',
  EDITOU_PRODUTO = 'EDITOU_PRODUTO',
  REGISTROU_PAGAMENTO_PRESENCIAL = 'REGISTROU_PAGAMENTO_PRESENCIAL',
}